---
title: "Past Perspectives"
---

A thorough and systematic understanding of personality will likely require the scientific method. But humans have only been applying something like the scientific method to understand personality and individual differences for a hundred years or so. So, for most of history, ideas about personality have been largely nonscientific. What can we learn from these past perspectives on personality that can give is a better appreciation for scientific approaches to understanding personality?

For one, we might just find it interesting to know how long humans have been trying to understand personality and individual differences. If humans around the world thought about personality for a long time, perhaps this suggests that personality differences have been important to humans for a long time. On the other hand, if caring about personality is a more recent phenomenon, maybe personality differences are only an important factor in the contemporary world for some reason.

Second, getting a sense of how long people have been thinking about personality can help us avoid hindsight bias, which is the feeling that things are obvious or easy after we've already learned about them or finished the task. By learning about past perspectives on personality, we can appreciate just how long people have been trying to understand personality---arguably without making much progress. When we see what past perspectives on personality generally were, it will be clear that things we learn about personality are not in fact obvious.

Third, examining how long people have been trying to understand personality and seeing how little progress has been made can help us appreciate that studying personality, or really any aspect of human psychology, is hard! We humans have unlocked many secrets of the universe: we've sent people into space, we've split the atom, we've created vaccines to nullify many dangerous diseases, we've created machines to talk to people anywhere in the world; but we can barely begin to understand the personalities and psychology of the humans that achieved these feats. Personality is largely still a mystery.

So, how long have humans been thinking about personality? What were some perspectives on personality in the past? Let's explore.

## Is Personality Ancient?

### Personality in the Oldest Written Story

The oldest written story we have evidence for is the *Epic of Gilgamesh*. It is a Mesopotamian story found written on stone tablets that date back to around 2200 BCE --- that's over 4000 years ago! And the story itself was probably transmitted verbally for a long time before it was written down.

The story is about an ancient king, Gilgamesh. In the beginning of the story, Gilgamesh is generally making life miserable for his subjects. The gods create a rival, Enkidu, to stop Gilgamesh. But Gilgamesh ends up beating Enkidu when they fight. So, naturally, they become best buds. Gilgamesh and Enkidu have many epic adventures until Enkidu dies. Gilgamesh then spends the rest of the story grieving and obsessing over his own mortality. He goes through a series of trials and tribulations in search of a way to defeat death, before ultimately making peace with his mortality.

The obvious takeaway from the story is that death is inevitable, and we should enjoy life while we can. But we could also view it as a story about personality change. Gilgamesh's behavior and feelings towards others changes quite a bit from the beginning to end: he started out a terrible person trying to control everyone and everything, and in the end he makes peace with his own mortality. Maybe the real epic of Gilgamesh is the personality change along the way.

But were the ancient humans who wrote down the epic including information about the characters personality? Du et al. (2023) examined the Epic of Gilgamesh to see what personality relevant information it contained and how that information might have changed as it was transcribed over the course of 1000 or so years. They found that even the earliest version of the story contained person descriptor words that are relevant to personality. Moreover, the number of personality descriptor words increased over time in different versions of the story. Thus, it appears that even 2000 years ago, humans wanted to know about others' personality.

### What About Earlier?

The Epic of Gilgamesh is old but not super old. Humans have existed for at least 200,000 years. Did super ancient humans care about individual differences and have ideas about personality? This is a difficult question to answer because we can't look back in time to see what they thought. But I think we can be fairly certain that our ancestors cared about personality for several reasons. Below I outline some reasons to think that personality differences existed and were important enough to care about throughout deep in our evolutionary past.

As far as we know, ancient humans were not clones, so they probably would not have been identical in every way. Individual differences in cognition and behavior would almost certainly have existed. Ancient humans had to make lots of decisions about others that would have impacted their survival and reproductive success: who is a good mate? Who is a good hunting partner? Who is a reliable cooperator? Who is a good worker? Knowing about differences in cognition and behavior between people is information that would be useful for our ancestors to determine the answers to those questions. Because of the way natural selection works (which we'll unpack in a later chapter), it would be surprising if our brains didn't evolve to detect differences between people that are relevant to solving problems of survival and reproduction.

As we'll see in the next chapter, personality as we know it depends largely on language. Language is probably at least 100,000 years old. Once language evolved, it would have become possible, at least in principle, to share information about personality attributes of others. Moreover, as language became more refined, our ability to communicate and think about the small differences between people would have become more refined as well. Thus, language and personality concepts could have coevolved culturally in a feedback loop: more fine-grained language could make it possible to identify small differences, and identifying small differences could lead to more fine-grained language concepts.

Of course, this is all a "just-so-story". But I can't really come up with a good reason why our ancestors wouldn't have paid attention to personality, and why personality concepts wouldn't have emerged in language fairly early on. Ultimately, I think it's pretty safe to say that humans have been thinking about personality and individual differences, at least implicitly or unconsciously, for a very very very long time. But what can we know about what these ancient humans thought about personality?

## A Nonexhaustive History of Historical Personality Perspectives

### A Note on Missing Data

Personality doesn't fossilize. We can only learn about what ancient humans thought about personality if those ancient humans happened to record their thoughts on material that would last long enough for us to find it. The overwhelming majority of personality-relevant information about cultures from around the world are lost to time.

So, we don't have data on what most cultures thought of personality. For example, we don't have good evidence for what indigenous Californians thought about personality in the thousands of years before colonization. But absence of evidence is not evidence of absence.

It is important to appreciate that the cultures we do have data from may not be representative of all human cultures that have ever existed. Still, by looking at the data we do have, perhaps we can start to get a sense of what sorts of things ancient humans might have thought about personality.

### Ideal Personalities

Ancient Confucian writings going back to 500 BCE discuss the concept of *Junzi*, which could be thought of as the closest any individual person could get to the ideal personality. Junzi has three components: *Ren* (benevolence), *Zhi* (wisdom), and *Yong* (courage). Under this view, people could cultivate different levels of each component and each component is causally related to one's behavior and thought. In contrast to Junzi, Confucian writings also discuss a personality concept of small-mindedness or pettiness, called *xiaoren.*

The Bhagavad-Gita, an ancient Hindu text going back to around 200 BCE talks about personality being composed of three "modes", the *Tri Gunas*. The three modes are: *sattva* (holiness), *rajas* (desire), and *tamas* (darkness). In this belief system, a person's actions are determined by the dominant mode. The relative dominance of each mode could be attributed to many things: mystic formulas, occupation, birth, ancestry, thought, etc.

### Humorous Humorism

Humorism is the belief that illnesses and differences in behavior correspond to the balance of four fluids ("humors") in the body: yellow bile in the liver; black bile from the kidneys; phlegm from the lungs; and blood from the heart. This belief system is often attributed to the ancient Greek physician-philosophers Hippocrates and Galen. But beliefs like humourism may actually go back further to ancient Mesopotamia or Egypt.

Under this view, each of the four humors corresponded to a different "temperament", or characteristic patterns of behavior---much like a personality trait. Too much yellow bile supposedly leads to a choleric temperament, which is passionate, brave, and determined. Too much black bile leads to a melancholic temperament, which consists of being detached, worried, or unhappy. Too much blood led to sanguine temperament, which tends to be joyful, eager, and optimistic. And too much phlegm led to a phlegmatic temperament of peace, dependability, and thoughtfulness. So, next time you feel sad, just find a way to increase your blood-to-black-bile ratio.

These beliefs might sound humorous to us now, but humorism was prevalent for over 1,000 years and continued to be popular through the Middle Ages. It wasn't until the theory of germs was developed that humourism's influence on medicine was remedied. This is good opportunity to reflect with humility on our own popular theories and beliefs; there could be many popular ideas about personality today that could seem as ridiculous to future generations as humorism does to us.

### Freud and the Neo-Freudians

#### Freud and Psychosexual Stages of Personality Development

According to Freud, our personality develops from a conflict between two forces: our biological aggressive and pleasure-seeking drives versus our internal (socialized) control over these drives. Our personality is the result of our efforts to balance these two competing forces. Freud suggested that we can understand this by imagining three interacting systems within our minds. He called them the id, ego, and superego.

The unconscious id contains our most primitive drives or urges and is present from birth. It directs impulses for hunger, thirst, and sex. Freud believed that the id operates on what he called the "pleasure principle," in which the id seeks immediate gratification. Through social interactions with parents and others in a child's environment, the ego and superego develop to help control the id. The superego develops as a child interacts with others, learning the social rules for right and wrong. The superego acts as our conscience; it is our moral compass that tells us how we should behave. It strives for perfection and judges our behavior, leading to feelings of pride or---when we fall short of the ideal---feelings of guilt. In contrast to the instinctual id and the rule-based superego, the ego is the rational part of our personality. It's what Freud considered to be the self, and it is the part of our personality that is seen by others. Its job is to balance the demands of the id and superego in the context of reality; thus, it operates on what Freud called the "reality principle." The ego helps the id satisfy its desires in a realistic way.

The id and superego are in constant conflict. The id wants instant gratification regardless of the consequences, but the superego tells us that we must behave in socially acceptable ways. Thus, the ego's job is to find the middle ground. It helps satisfy the id's desires in a rational way that will not lead us to feelings of guilt. According to Freud, a person who has a strong ego, which can balance the demands of the id and the superego, has a healthy personality. Freud maintained that imbalances in the system can lead to neurosis (a tendency to experience negative emotions), anxiety disorders, or unhealthy behaviors. For example, a person who is dominated by their id might be narcissistic and impulsive. A person with a dominant superego might be controlled by feelings of guilt and deny themselves even socially acceptable pleasures; conversely, if the superego is weak or absent, a person might become a psychopath. An overly dominant superego might be seen in an over-controlled individual whose rational grasp on reality is so strong that they are unaware of their emotional needs, or, in a neurotic who is overly defensive (overusing ego defense mechanisms).

Freud believed that personality develops during early childhood: Childhood experiences shape our personalities as well as our behavior as adults. He asserted that we develop via a series of stages during childhood. Each of us must pass through these childhood stages, and if we do not have the proper nurturing and parenting during a stage, we will be stuck, or fixated, in that stage, even as adults.

In each **psychosexual stage of development**, the child's pleasure-seeking urges, coming from the id, are focused on a different area of the body, called an erogenous zone. The stages are oral, anal, phallic, latency, and genital.

Freud's psychosexual development theory is quite controversial. To understand the origins of the theory, it is helpful to be familiar with the political, social, and cultural influences of Freud's day in Vienna at the turn of the 20th century. During this era, a climate of sexual repression, combined with limited understanding and education surrounding human sexuality, heavily influenced Freud's perspective. Given that sex was a taboo topic, Freud assumed that negative emotional states (neuroses) stemmed from suppression of unconscious sexual and aggressive urges. For Freud, his own recollections and interpretations of patients' experiences and dreams were sufficient proof that psychosexual stages were universal events in early childhood. (Note that such self-reflection would hardly even be considered a good a starting point for developing a theory of personality, let alone sufficient evidence for the theory.)

##### Oral Stage

In the oral stage (birth to 1 year), pleasure is focused on the mouth. Eating and the pleasure derived from sucking (nipples, pacifiers, and thumbs) play a large part in a baby's first year of life. At around 1 year of age, babies are weaned from the bottle or breast, and this process can create conflict if not handled properly by caregivers. According to Freud, an adult who smokes, drinks, overeats, or bites her nails is fixated in the oral stage of her psychosexual development; she may have been weaned too early or too late, resulting in these fixation tendencies, all of which seek to ease anxiety.

##### Anal Stage

After passing through the oral stage, children enter what Freud termed the anal stage (1--3 years). In this stage, children experience pleasure in their bowel and bladder movements, so it makes sense that the conflict in this stage is over toilet training. Freud suggested that success at the anal stage depended on how parents handled toilet training. Parents who offer praise and rewards encourage positive results and can help children feel competent. Parents who are harsh in toilet training can cause a child to become fixated at the anal stage, leading to the development of an anal-retentive personality. The anal-retentive personality is stingy and stubborn, has a compulsive need for order and neatness, and might be considered a perfectionist. If parents are too lenient in toilet training, the child might also become fixated and display an anal-expulsive personality. The anal-expulsive personality is messy, careless, disorganized, and prone to emotional outbursts.

##### Phallic Stage

Freud's third stage of psychosexual development is the phallic stage (3--6 years), corresponding to the age when children become aware of their bodies and recognize the differences between boys and girls. The erogenous zone in this stage is the genitals. Conflict arises when the child feels a desire for the opposite-sex parent, and jealousy and hatred toward the same-sex parent. For boys, this is called the Oedipus complex, involving a boy's desire for his mother and his urge to replace his father who is seen as a rival for the mother's attention. At the same time, the boy is afraid his father will punish him for his feelings, so he experiences *castration anxiety*. The Oedipus complex is successfully resolved when the boy begins to identify with his father as an indirect way to have the mother. Failure to resolve the Oedipus complex may result in fixation and development of a personality that might be described as vain and overly ambitious.

Girls experience a comparable conflict in the phallic stage---the Electra complex. The Electra complex, while often attributed to Freud, was actually proposed by Freud's protégé, Carl Jung (Jung & Kerenyi, 1963). A girl desires the attention of her father and wishes to take her mother's place. Jung also said that girls are angry with the mother for not providing them with a penis---hence the term *penis envy*.

##### Latency Period

Following the phallic stage of psychosexual development is a period known as the latency period (6 years to puberty). This period is not considered a stage, because sexual feelings are dormant as children focus on other pursuits, such as school, friendships, hobbies, and sports. Children generally engage in activities with peers of the same sex, which serves to consolidate a child's gender-role identity.

##### Genital Stage

The final stage is the genital stage (from puberty on). In this stage, there is a sexual reawakening as the incestuous urges resurface. The young person redirects these urges to other, more socially acceptable partners (who often resemble the other-sex parent). People in this stage have mature sexual interests, which for Freud meant a strong desire for the opposite sex. Individuals who successfully completed the previous stages, reaching the genital stage with no fixations, are said to be well-balanced, healthy adults.

#### Neo-Freudians

Freud's ideas inspired and influenced many subsequent psychologists, mostly through disagreements. The followers of Freud, who are often deemed "neo-Freudians", typically agreed with Freud that there are unconscious urges that are important for behavior and that development mattered for personality, but they often disagreed about the specifics. Some notable neo-freudians that we will examine here are Alfred Adler, Karen Horney, and Carl Jung.

##### Alfred Adler: Inferiority Avoidance

Alfred Adler disagreed with Freud's proposal that sexual libido and aggression were the main driving forces of human behavior. Adler argued instead that the need to be superior to others, or at least to avoid being inferior to others is the main driver of behavior and personality.

Adler also proposed the idea that birth order shapes our personality. He suggested that older siblings, who start out as the focus of their parents' attention but must share that attention once a new child joins the family, compensate by becoming overachievers. The youngest children, according to Adler, may be spoiled, leaving the middle child with the opportunity to minimize the negative dynamics of the youngest and oldest children. Despite popular attention, research has not provided much support for Adler's hypotheses about birth order.

##### Karen Horney: Need for Security and Support

Karen Horney was one of the first women trained as a Freudian psychoanalyst. Horney disagreed with the Freudian idea that girls have penis envy and are jealous of male biological features. According to Horney, any jealousy is most likely culturally based, due to the greater privileges that males often have in a patriarchal society. She further countered that men have womb envy because they cannot give birth.

Like Adler, Horney disagreed with Freud's focus on sexual urges and aggression. Her theory of personality development focused on the role of unconscious anxiety. She suggested that normal growth can be blocked by basic anxiety stemming from needs not being met, such as childhood experiences of loneliness and/or isolation Horney suggested that people cope with these anxieties and desire for security with three main coping styles: moving towards people; moving away from people; and moving against people. Horney believed these three styles are normal ways in which people cope with day-to-day problems but that inflexibility in applying the strategies can lead to neurotic behavior and alienation from others.

##### Carl Jung: Archetypes, Attitudes

Jung's split from Freud was based on two major disagreements. First, Jung, like Adler and Erikson, did not accept that sexual drive was the primary motivator in a person's mental life. Second, although Jung agreed with Freud's concept of a personal unconscious, he thought it to be incomplete. In addition to the personal unconscious, Jung focused on the collective unconscious.

The collective unconscious is a universal version of the personal unconscious, holding mental patterns, or memory traces, which are common to all of us. These ancestral memories, which Jung called **archetypes**, are represented by universal themes in various cultures, as expressed through literature, art, and dreams (Jung). Jung said that these themes reflect common experiences of people the world over, such as facing death, becoming independent, and striving for mastery. Jung believed that through biology, each person is handed down the same themes and that the same types of symbols---such as the hero, the maiden, the sage, and the trickster---are present in the folklore and fairy tales of every culture. In Jung's view, the task of integrating these unconscious archetypal aspects of the self is part of the self-realization process in the second half of life. With this orientation toward self-realization, Jung parted ways with Freud's belief that personality is determined solely by past events and anticipated the humanistic movement with its emphasis on self-actualization and orientation toward the future.

Jung also proposed two attitudes or approaches toward life: extroversion and introversion. These ideas are considered Jung's most important contributions to the field of personality psychology, as almost all models of personality now include these concepts. If you are an extrovert, then you are a person who is energized by being outgoing and socially oriented: You derive your energy from being around others. If you are an introvert, then you are a person who may be quiet and reserved, or you may be social, but your energy is derived from your inner psychic activity. Jung believed a balance between extroversion and introversion best served the goal of self-realization.

Another concept proposed by Jung was the persona, which he referred to as a mask that we adopt. According to Jung, we consciously create this persona; however, it is derived from both our conscious experiences and our collective unconscious. What is the purpose of the persona? Jung believed that it is a compromise between who we really are (our true self) and what society expects us to be. We hide those parts of ourselves that are not aligned with society's expectations.

Jung's view of extroverted and introverted types inspired a mother-daughter duo to create a personality test, which is known as the *Myers-Briggs Type Indicator* (MBTI). This questionnaire is loosely based on Jung's theories and describes a person's degree of introversion versus extroversion, thinking versus feeling, intuition versus sensation, and judging versus perceiving. While very popular on dating websites and even in many companies, there is very little evidence that the MBTI is a reliable or valid tool to measure personality. These are concepts we will learn more about in a later chapter. One of the main issues with the MBTI is that it creates a *typology*---it puts people into discrete categories to describe their personality. But human personalities exist on a continuum. So, any effort to create distinct categories will necessarily introduce arbitrary boundaries that lead to less accurate description of personality.

## Conclusion

Humans have probably cared about personality for very long time. And we've been trying to understand personality for at least a few thousand years. However, as this chapter shows, many historical approaches to understanding personality have been non-scientific. Most of the historical beliefs and so-called theories about personality were based on self-reflection and opinions about what makes a healthy or virtuous person. But this approach to understanding personality leaves out a lot of the variation in human behavior that makes up the many diverse personalities that exist. The scientific approach to understanding personality that we will explore throughout the rest of the chapters brings large amounts of data to allow us to systematically study personality, while hopefully making it harder for our own subjective biases and beliefs to creep in.

## References
Du, A. H., Karl, J. A., Fetvadjiev, V., Luczak-Roesch, M., Pirngruber, R., & Fischer, R. (2023). Tracing the evolution of personality cognition in early human civilisations: A computational analysis of the Gilgamesh epic. *European Journal of Personality*.

The sections on Freud and the neo-Freudians are largely reproduced with minor changes from associated units of the Open Educational Resources available at [https://oercommons.org/courseware/unit/8482](https://oercommons.org/courseware/unit/8482). Those units are published under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/), but no authors are listed, so it is not clear how to give a proper citation.
