---
output:
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "Curriculum Vitae (Abbreviated)"
author: "Patrick Durkee"
date: "`r format(Sys.time(), '%B, %Y')`"
fontawesome: yes
email: pdurkee@csufresno.edu
web: pdurkee.com
github: durkeepk
twitter: durkeepk
updated: yes

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: black
urlcolor: black

header-includes:
  - |
    % Macro for author name (use everywhere instead of writing it out)
    \newcommand{\me}{\textbf{Durkee, P. K.}}
    % load marginal-note helpers (marginnote is more robust inside Pandoc-generated docs)
    \usepackage{marginnote}
    % If your template already loads a FontAwesome package, you can remove the next line.
    \usepackage{fontawesome}
    % Define pubitem macro for consistent hanging + marginal icons
    \newcommand{\pubitem}[3]{%
      \noindent
      \hangindent=0.5in \hangafter=1
      \marginnote{\scriptsize #2}[-1em]%
      #1\enspace #3\par
    }
---

\definecolor{light-gray}{gray}{.5}

# PROFESSIONAL APPOINTMENTS

Assistant Professor of Psychology, \textit{California State University, Fresno} \hfill \textcolor{light-gray}{2023 - Present}

Research Fellow, \textit{Institute for Advanced Study in Toulouse, France} \hfill \textcolor{light-gray}{2022 - 2023}

Adjunct Professor of Psychology, \textit{Texas State University} \hfill \textcolor{light-gray}{2021 - 2022}

# EDUCATION

Ph.D., Psychology, \textit{The University of Texas at Austin} \hfill \textcolor{light-gray}{2021}

M.A., Experimental Psychology, \textit{California State University, Fullerton} \hfill
\textcolor{light-gray}{2017}

B.A., Psychology, \textit{California State University, Fullerton} \hfill \textcolor{light-gray}{2015}

# PUBLICATIONS

^Contribution^ ^Notes:^
^\faLightbulbO^ ^=^ ^Concept/Design^^;^
^\faTable^ ^=^ ^Data^ ^Collection^^;^
^\faBarChart^ ^=^ ^Analysis^^/^^Visualization^^;^
^\faPencil^ ^=^ ^Writing^
\newline 
^Paper^ ^Notes:^
^\faRegistered^ ^=^ ^Registered^ ^Report^^;^
<!-- ^\faCommentsO^ ^=^ \textit{^Commentary/Reply^}^;^ -->
^\faCheckCircle^ ^=^ ^Preregistered^^;^
^\faDatabase^ ^=^ ^Open^ ^Dataset^^;^
^\faFileCodeO^ ^=^ ^Open^ ^Code^
<!-- ^\faFileTextO^ ^=^ \textit{^PDF^} -->
\newline 
^Authorship^ ^Notes:^ 
^\faUnsorted^ ^=^ ^Shared^ ^First^ ^Authorship^^;^
^\textdagger^ ^=^ ^Undergraduate^ ^Mentee^^;^
^\textdaggerdbl^ ^=^ ^Graduate^ ^Mentee^

\textcolor{light-gray}{30 peer reviewed articles, including:}

\pubitem{}{\faLightbulbO\faBarChart\faPencil\\\textsuperscript{\faCheckCircle\faDatabase\faFileCodeO}}{\me, Graves\textsuperscript{\textdagger}, P. A., Rodriguez\textsuperscript{\textdaggerdbl}, N. R. (2026). Toward a Mechanistic Account of Personality: A Case Study of Competitor Derogation Accuracy and the Dark Triad. \textit{Evolution and Human Behavior}.}

\pubitem{}{\faLightbulbO\faBarChart\faPencil\\\textsuperscript{\faDatabase\faFileCodeO}}{\me, Buss, D. M. (2026). Hierarchy Navigation: Individual Differences in Tactics, Strategies, and Traits. \textit{Human Nature}.}

\pubitem{}{\faLightbulbO\faBarChart\faPencil\\\textsuperscript{\faDatabase\faFileCodeO}}{\me{} (2025). Measuring Personality Traits: Simulations Exploring (Mis)Alignment Between Methods and Measurands. \textit{Journal of Research in Personality}.}

\pubitem{}{\faLightbulbO\faPencil}{\href{https://www.sciencedirect.com/science/article/pii/S1090513824000461?dgcid=author}{\me, Lukaszewski, A. L. (2024). Deconstructing “dominance” to refine leadership research. \textit{Evolution and Human Behavior}.}}

\pubitem{}{\faLightbulbO\faTable\faBarChart\faPencil\\\textsuperscript{\faRegistered\faDatabase\faFileCodeO}}{\me, Lukaszewski, A. L., Buss, D. M. (2023). \href{https://www.cambridge.org/core/services/aop-cambridge-core/content/view/F16454C7E058347A01F94E64565CBF19/S2513843X23000129a.pdf}{Status-impact assessment: Is accuracy linked with status motivations? \textit{Evolutionary Human Sciences}.}}


\pubitem{}{\faLightbulbO\faTable\faBarChart\faPencil\\\textsuperscript{\faDatabase\faFileCodeO}}{\me, Lukaszewski, A. W., von Rueden, C., Gurven, M., Buss, D. M., Tucker-Drob, E. M. (2022). \href{http://www.pdurkee.com/files/pubs/Durkee_etal_2022_PsychScience.pdf}{Niche diversity predicts personality structure across 115 nations. \textit{Psychological Science}.}}

\pubitem{}{\faLightbulbO\faBarChart\faPencil\\\textsuperscript{\faRegistered\faDatabase\faFileCodeO}}{\me, Ayers, J. D. (2021). \href{http://www.pdurkee.com/files/pubs/Durkee&Ayers2021_fWHR_EHB.pdf}{Is facial width-to-height ratio reliably associated with social inferences? \textit{Evolution and Human Behavior}.}}

\pubitem{}{\faLightbulbO\faTable\faBarChart\faPencil\\\textsuperscript{\faDatabase\faFileCodeO}}{\me, Lukaszewski, A. L., Buss, D. M. (2020). \href{http://www.pdurkee.com/files/pubs/DurkeeLukaszewskiBuss2020_PsychologicalFoundationsofHumanStatusAllocation.pdf}{Psychological foundations of human status allocation. \textit{Proceedings of the National Academy of Sciences}.}}

\pubitem{}{\faBarChart\faPencil\\\textsuperscript{\faDatabase\faFileCodeO}}{Buss, D. M.\textsuperscript{\faUnsorted}, \me\textsuperscript{\faUnsorted}, Shackelford, T. K., Schmitt, D. P., Bowdle, B. F., Brase, G. L., Choe, J. C., Trofimova, I. (2020). \href{http://www.pdurkee.com/files/pubs/Buss&Durkee_etal_HumanStatusCriteria.pdf}{Human status criteria: Sex differences and similarities across 14 nations. \textit{Journal of Personality and Social Psychology}.}}

\pubitem{}{\faLightbulbO\faTable\faBarChart\faPencil\\\textsuperscript{\faCheckCircle\faDatabase\faFileCodeO}}{\me, Lukaszewski, A. L., Buss, D. M. (2019). \href{http://www.pdurkee.com/files/pubs/DurkeeLukaszewskiBuss_PrideShame_2019.pdf}{Pride and shame: Key components of a culturally universal status management system. \textit{Evolution and Human Behavior}.}}

\pubitem{}{\faLightbulbO\faTable\faBarChart\faPencil\\\textsuperscript{\faDatabase}}{\me\textsuperscript{\faUnsorted}, Goetz, A. T.\textsuperscript{\faUnsorted}, Lukaszewski, A. W. (2018). \href{http://www.pdurkee.com/files/pubs/DurkeeGoetzLukaszewski_2018.pdf}{Formidability assessment mechanisms: Examining their speed and automaticity. \textit{Evolution and Human Behavior}.}}

# PRESENTATIONS

\textcolor{light-gray}{14 Invited Talks, including:}

\pubitem{}{}{\me{} (October, 2025). \textit{Prediction and Causal Inference as Subtasks of Adaptive Challenges}. Center for the Study of Human Nature, CSU Fullerton.}

\pubitem{}{}{\me{} (March, 2025). \textit{Differentiating hierarchy navigation emotions}. Oklahoma Center for Evolutionary Analysis (OCEAN), Oklahoma State.}

\pubitem{}{}{\me{} (February, 2025). \textit{Linking adaptationist models of emotion to lexical personality traits}. SPSP Evolutionary Psychology Preconference, Denver, CO.}

\pubitem{}{}{\me{} (June, 2023). \textit{Preferences and Personality}. Institute for Advanced Study in Toulouse, France.}

\pubitem{}{}{\me{} (March, 2023). \textit{Improving Personality Measurement}. Center for the Study of Human Nature, CSU Fullerton.}

\textcolor{light-gray}{15 Conference Talks, including:}

\pubitem{}{}{\me{} (2025, February). \textit{Navigating hierarchies: Cross-national examination of cues informing status criteria inference}. Podium, SPSP, Denver, CO.}

\pubitem{}{}{\me{} (2023, June). \textit{Status impact assessment: Is accuracy linked with status motives?}. Podium, HBES, Palm Springs. [Finalist for Postdoctoral Research Award]}

\textcolor{light-gray}{Posters: 37 total (2015--2025); selected posters and PDFs online.}

# SELECTED TEACHING

\textcolor{light-gray}{Instructor of Record}

Advanced Seminar on Personality and Social Psychology (grad seminar)
Theories of Emotion \newline
Causal Inference in Psychology (grad seminar)\newline
Undergraduate Honors Seminar\newline
Personality Psychology\newline
Advanced Statistical Methodology in R (online)

\textcolor{light-gray}{Training}

EEOD Training \hfill \textcolor{light-gray}{Fall 2025} \newline
Advancing Inclusive Mentoring (AIM) Program \hfill \textcolor{light-gray}{Fall 2024} \newline
Introduction to Teaching Online Using QLT \hfill \textcolor{light-gray}{Fall 2023}

# SELECTED GRANTS & AWARDS

Besample "Beyond the West" Research Grant \hfill \textcolor{light-gray}{Spring 2023} \newline
KindFund Research Grant \hfill \textcolor{light-gray}{Fall 2021}

# SELECTED PROFESSIONAL SERVICE 

\textbf{Editorial Assistant}, \textit{Handbook of Human Mating}, Buss, D. M. (Ed.) \hfill \textcolor{light-gray}{2019--2021}

\textbf{Ad hoc reviewer (selected):} \textit{Evolution and Human Behavior}; \textit{Journal of Personality and Social Psychology (PPID)}; \textit{Perspectives on Psychological Science}; \textit{Psychological Science}; \textit{Journal of Personality}; \textit{PNAS}; \textit{Proceedings of the Royal Society B}; \textit{PLoS ONE} (+ others)

# PROFESSIONAL AFFILIATIONS

Society for Personality and Social Psychology (SPSP) \newline
Human Behavior and Evolution Society (HBES)

<!-- \textcolor{light-gray}{References available upon request.} -->

